AMCL parameters
tue-robotics/hero_bringup pull request #59
Opened 2020-07-18 08:12 UTC by MatthijsBurgh

2021-02-15 20:39 UTC, jlunenburg requested changes
Can you give a bit more explanation and context of this MR? I guess it refers to https://github.com/tue-robotics/hero_bringup/pull/59 . Maybe a bit more explanation when to use the new launch file

2021-03-30 16:47 UTC, MatthijsBurgh commented on parameters/world_modeling/world_model_plugin_localization.yaml
> +     recovery_alpha_slow: 0 #0.001
These have not really been tested, And therefore commented. These are the suggested values by the ROS AMCL.

2021-03-30 16:50 UTC, MatthijsBurgh commented
Updated the description of the PR

2021-11-30 19:10 UTC, ar13pit approved these changes

2021-11-30 19:50 UTC, merged